[[redirects]]
  from = "/pathx"
  to = "https://tranquil-river-53049-65f1a1de2e8e.herokuapp.com/tasks"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"